language: ruby

rvm:
   - 2.1
   - 2.2
   - 2.3
   - 2.4
   - 2.5
   - rbx-3
   - jruby-9.1

matrix:
   allow_failures:
      - rvm: rbx-3
   include:
      - rvm: 2.5
        script: "bundle exec rubocop"

bundler_args: "--without=development"

sudo: false

script: "bundle exec rspec"
