language: ruby

rvm:
   - 2.5
   - 2.6
   - 2.7

matrix:
   include:
      - rvm: 2.5
        script: "bundle exec rubocop"

bundler_args: "--without=development"

sudo: false

script: "bundle exec rspec"
