# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cadenza}
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["William Howard"]
  s.date = %q{2011-02-14}
  s.email = %q{whoward.tke@gmail.com}
  s.homepage = %q{http://github.com/whoward/Cadenza}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Powerful text templating language similar to Smarty/Liquid/Django}
  s.test_files = [
    "spec/api/implied_globals_spec.rb",
    "spec/lexer/counter_spec.rb",
    "spec/lexer/lexer_spec.rb",
    "spec/lexer/token_spec.rb",
    "spec/lexer/whitespace_spec.rb",
    "spec/parser/inject_statement_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

